import type { Plan, VpnKey, User, SupportTicket } from './types'

export const PLANS: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 50,
    period: '/ мес',
    periodMonths: 1,
    features: [
      '1 устройство',
      '5 локаций',
      'Базовая скорость',
      'Без рекламы',
    ],
    devicesCount: 1,
    speedLabel: '50 Мбит/с',
  },
  {
    id: 'turbo',
    name: 'Turbo',
    price: 149,
    period: '/ мес',
    periodMonths: 1,
    features: [
      '3 устройства',
      '15 локаций',
      'Высокая скорость',
      'Без рекламы',
      'Kill Switch',
    ],
    popular: true,
    badge: 'Популярный',
    devicesCount: 3,
    speedLabel: '200 Мбит/с',
  },
  {
    id: 'phantom',
    name: 'Phantom',
    price: 249,
    period: '/ мес',
    periodMonths: 1,
    features: [
      '5 устройств',
      '30+ локаций',
      'Макс. скорость',
      'Без рекламы',
      'Kill Switch',
      'Double VPN',
    ],
    badge: 'PRO',
    devicesCount: 5,
    speedLabel: '500 Мбит/с',
  },
  {
    id: 'ghost-year',
    name: 'Ghost Year',
    price: 1990,
    period: '/ год',
    periodMonths: 12,
    features: [
      '10 устройств',
      'Все локации',
      'Макс. скорость',
      'Без рекламы',
      'Kill Switch',
      'Double VPN',
      'Приоритетная поддержка',
      'Выделенный IP',
    ],
    badge: '-33%',
    discount: 33,
    devicesCount: 10,
    speedLabel: 'Без лимита',
  },
]

export const MOCK_USER: User = {
  id: '1',
  telegramId: '123456789',
  username: 'ghost_user',
  displayName: 'Ghost User',
  role: 'owner',
  createdAt: '2025-01-15',
  subscription: {
    id: 'sub-1',
    planId: 'turbo',
    status: 'active',
    expiresAt: '2026-03-15',
    vpnKey: 'vless://abc123...xyz789',
    autoRenew: true,
  },
}

export const MOCK_VPN_KEYS: VpnKey[] = [
  {
    id: 'key-1',
    key: 'vless://user1@server1.ghostvpn.io:443?type=ws&security=tls',
    userId: '1',
    username: 'ghost_user',
    planName: 'Turbo',
    createdAt: '2025-12-01',
    expiresAt: '2026-03-15',
    status: 'active',
  },
  {
    id: 'key-2',
    key: 'vless://user2@server2.ghostvpn.io:443?type=ws&security=tls',
    userId: '2',
    username: 'cyber_fox',
    planName: 'Phantom',
    createdAt: '2025-11-20',
    expiresAt: '2026-02-20',
    status: 'active',
  },
  {
    id: 'key-3',
    key: 'vless://user3@server1.ghostvpn.io:443?type=ws&security=tls',
    userId: '3',
    username: 'shadow_net',
    planName: 'Starter',
    createdAt: '2025-10-05',
    expiresAt: '2025-12-05',
    status: 'expired',
  },
]

export const MOCK_USERS: User[] = [
  MOCK_USER,
  {
    id: '2',
    telegramId: '987654321',
    username: 'cyber_fox',
    displayName: 'Cyber Fox',
    role: 'admin',
    createdAt: '2025-02-10',
    subscription: { id: 'sub-2', planId: 'phantom', status: 'active', expiresAt: '2026-02-20', autoRenew: true },
  },
  {
    id: '3',
    telegramId: '555666777',
    username: 'shadow_net',
    displayName: 'Shadow Net',
    role: 'support',
    createdAt: '2025-03-05',
    subscription: { id: 'sub-3', planId: 'starter', status: 'expired', expiresAt: '2025-12-05', autoRenew: false },
  },
  {
    id: '4',
    telegramId: '111222333',
    username: 'neo_matrix',
    displayName: 'Neo Matrix',
    role: 'user',
    createdAt: '2025-06-15',
  },
  {
    id: '5',
    telegramId: '444555666',
    username: 'dark_angel',
    displayName: 'Dark Angel',
    role: 'user',
    createdAt: '2025-08-20',
    subscription: { id: 'sub-5', planId: 'turbo', status: 'active', expiresAt: '2026-04-01', autoRenew: true },
  },
]

export const MOCK_TICKETS: SupportTicket[] = [
  {
    id: 'ticket-1',
    userId: '4',
    username: 'neo_matrix',
    subject: 'Не подключается VPN в Германии',
    status: 'open',
    createdAt: '2026-02-14',
  },
  {
    id: 'ticket-2',
    userId: '5',
    username: 'dark_angel',
    subject: 'Низкая скорость на тарифе Turbo',
    status: 'in-progress',
    assignedTo: 'shadow_net',
    createdAt: '2026-02-13',
  },
  {
    id: 'ticket-3',
    userId: '1',
    username: 'ghost_user',
    subject: 'Вопрос про Double VPN',
    status: 'resolved',
    assignedTo: 'shadow_net',
    createdAt: '2026-02-10',
  },
]

export const LOCATIONS = [
  { country: 'Нидерланды', flag: 'NL', ping: 24, load: 35 },
  { country: 'Германия', flag: 'DE', ping: 31, load: 52 },
  { country: 'Финляндия', flag: 'FI', ping: 18, load: 28 },
  { country: 'США', flag: 'US', ping: 89, load: 67 },
  { country: 'Япония', flag: 'JP', ping: 142, load: 41 },
  { country: 'Сингапур', flag: 'SG', ping: 128, load: 33 },
]
